#!/bin/bash

[ -f /etc/conf.d/tomcat ] && . /etc/conf.d/tomcat

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting Tomcat"
    /usr/share/tomcat/bin/jsvc \
      -user tomcat \
      -Dcatalina.home=/usr/share/tomcat \
      -Dcatalina.base=/usr/share/tomcat \
      -Djava.io.tmpdir=/tmp \
      -wait 10 \
      -pidfile /var/run/tomcat.pid \
      -errfile $ERROR_FILE \
      $CATALINA_OPTS \
      -cp /usr/share/tomcat/bin/commons-daemon.jar:/usr/share/tomcat/bin/bootstrap.jar \
      org.apache.catalina.startup.Bootstrap

    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon tomcat
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Tomcat"
    /usr/share/tomcat/bin/jsvc \
      -stop \
      -pidfile /var/run/tomcat.pid \
      org.apache.catalina.startup.Bootstrap

    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon tomcat
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
