#!/bin/bash

[ -f /etc/conf.d/tomcat5.5 ] && . /etc/conf.d/tomcat5.5

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting Tomcat"
    /opt/tomcat/bin/jsvc \
      -user tomcat \
      -home $TOMCAT_JAVA_HOME \
      -Dcatalina.home=/opt/tomcat \
      -Dcatalina.base=/opt/tomcat \
      -Djava.io.tmpdir=/opt/tomcat/temp \
      -wait 10 \
      -pidfile /var/run/tomcat5.5.pid \
      -errfile /opt/tomcat/logs/catalina.log \
      $CATALINA_OPTS \
      -cp $TOMCAT_JAVA_HOME/lib/tools.jar:/opt/tomcat/bin/commons-daemon.jar:/opt/tomcat/bin/bootstrap.jar \
      org.apache.catalina.startup.Bootstrap

    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon tomcat5.5
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Tomcat"
    /opt/tomcat/bin/jsvc \
      -stop \
      -pidfile /var/run/tomcat5.5.pid \
      org.apache.catalina.startup.Bootstrap

    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon tomcat5.5
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
