#!/bin/bash

[ -f /etc/conf.d/tomcat5 ] && . /etc/conf.d/tomcat5

. /etc/rc.conf
. /etc/rc.d/functions

JSVC_BIN='/usr/share/tomcat5/bin/jsvc'
PID_FILE='/var/run/tomcat5.pid'
TOMCAT_DIR='/usr/share/tomcat5'

case "$1" in
  start)
    stat_busy "Starting Tomcat 5"
    $JSVC_BIN \
      -user tomcat5 \
      -Dcatalina.home=$TOMCAT_DIR \
      -Dcatalina.base=$TOMCAT_DIR \
      -Djava.io.tmpdir=/tmp \
      -wait 10 \
      -pidfile $PID_FILE \
      -errfile $ERROR_FILE \
      $CATALINA_OPTS \
      -cp $TOMCAT_DIR/bin/commons-daemon.jar:$TOMCAT_DIR/bin/bootstrap.jar \
      org.apache.catalina.startup.Bootstrap

    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon tomcat5
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Tomcat 5.5"
    $JSVC_BIN \
      -stop \
      -pidfile $PID_FILE \
      org.apache.catalina.startup.Bootstrap

    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon tomcat5
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
